import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { email, pdfBase64, statementId, walletAddress, verificationHash } = body;

    if (!email || !pdfBase64) {
      return NextResponse.json(
        { error: "Email and PDF data are required" },
        { status: 400 }
      );
    }

    // Attempt to use Resend if API key is available
    const resendKey = process.env.RESEND_API_KEY;
    if (!resendKey) {
      return NextResponse.json(
        { error: "Email service not configured" },
        { status: 503 }
      );
    }

    const { Resend } = await import("resend");
    const resend = new Resend(resendKey);

    await resend.emails.send({
      from: "Fundslip <statements@fundslip.xyz>",
      to: email,
      subject: `Your Fundslip Financial Statement — ${statementId}`,
      html: `
        <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 24px; color: #191c1e;">
          <div style="margin-bottom: 32px;">
            <h1 style="font-size: 24px; font-weight: 800; letter-spacing: -0.02em; margin: 0;">Fundslip</h1>
            <p style="font-size: 10px; text-transform: uppercase; letter-spacing: 0.1em; color: #434654; margin-top: 4px;">Asset Verification Report</p>
          </div>

          <p style="font-size: 14px; line-height: 1.6; color: #434654;">
            Your verifiable financial statement has been generated and is attached to this email as a PDF.
          </p>

          <div style="background: #f2f4f6; border-radius: 8px; padding: 20px; margin: 24px 0;">
            <p style="font-size: 9px; text-transform: uppercase; letter-spacing: 0.1em; color: #434654; font-weight: 700; margin: 0 0 8px;">Statement ID</p>
            <p style="font-size: 16px; font-weight: 700; margin: 0;">${statementId}</p>
          </div>

          <div style="background: #f2f4f6; border-radius: 8px; padding: 20px; margin: 24px 0;">
            <p style="font-size: 9px; text-transform: uppercase; letter-spacing: 0.1em; color: #434654; font-weight: 700; margin: 0 0 8px;">Verification Hash</p>
            <p style="font-family: 'Courier New', monospace; font-size: 11px; color: #434654; word-break: break-all; margin: 0;">${verificationHash}</p>
          </div>

          <p style="font-size: 12px; color: #747686; margin-top: 32px;">
            To verify this statement, visit <a href="https://fundslip.xyz/verify" style="color: #003499;">fundslip.xyz/verify</a>
          </p>

          <hr style="border: none; border-top: 1px solid #eceef0; margin: 32px 0;" />

          <p style="font-size: 10px; color: #747686;">
            Generated by Fundslip — fundslip.xyz<br/>
            Wallet: ${walletAddress}
          </p>
        </div>
      `,
      attachments: [
        {
          filename: `fundslip-statement-${statementId}.pdf`,
          content: pdfBase64,
        },
      ],
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Email send error:", error);
    return NextResponse.json(
      { error: "Failed to send email" },
      { status: 500 }
    );
  }
}
